bootstrap 導入
yanbaru-expert/gyakuten_clone_group36 pull request #14
Opened 2020-12-06 08:32 UTC by wkzyonna

【注意】不要なものは削って下さい

## 実装内容

原則，マークダウン記法のリストで記載すること

(例)

- リスト1
  - リスト1-1
  - リスト1-2  

## 参考資料

マークダウン記法のリンクを用いて記載すること

(例)

- ログイン機能
  - [やんばるCODEアプリ](https://arcane-gorge-21903.herokuapp.com/texts/219)

## チェックリスト

※ プルリクを出した後にクリックしてチェックを入れて下さい

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

## スクリーンショット（必要があれば）

## 備考（必要があれば）

2020-12-06 10:30 UTC, ajk0421 requested changes
実装確認の為の記述は、確認後削除するようにしましょう！

2020-12-06 10:30 UTC, ajk0421 commented on app/views/texts/index.html.erb
> +<button type="button" class="btn btn-primary">Primary</button>
```
<button type="button" class="btn btn-primary">Primary</button>
```
こちら必要なボタンでしょうか？

2020-12-06 14:45 UTC, wkzyonna reviewed
削除しました。
ご確認をお願いします。

2020-12-07 03:57 UTC, ajk0421 approved these changes
LGTM！マージしてください！

2020-12-07 07:45 UTC, merged