【途中】15_Railsテキスト教材一覧ページの実装
yanbaru-expert/gyakuten_clone_group36 pull request #19
Opened 2020-12-15 13:38 UTC by yusaku9106

##実装内容
-  Railsテキスト教材の一覧ページを作成

##未着手
- ジャンルによる表示出し分け
- ナビバーのリンク

## 詰まっていること
2点あります。
- cardsの高さが揃わない
添付のようにタイトルが複数行になる場合、高さが揃いません。 h-100等のクラスを入れるなど試行しましたが、反映はされるものの、見栄えが悪くなり、上手くいかない状況です。

- ジャンルによる表示出し分けの仕方がわからない
コントローラにて制御するのかと考えましたが、制御の仕方がイメージつきません。

2020-12-16 03:26 UTC, ajk0421 commented
>cardsの高さが揃わない

cssでheightを指定すると良いと思います！

>ジャンルによる表示出し分けの仕方がわからない

これは具体的にどういう実装がしたいですか？

2020-12-16 08:43 UTC, yusaku9106 commented
ご返信ありがとうございます。

> cssでheightを指定すると良いと思います！
cssの記載進めてみます。

> これは具体的にどういう実装がしたいですか？
→csvで入れた情報にgenreカラムがあります。そのカラムにタスク指定外の項目があり("Php"、"AWS")、指定外のテキスト教材は一覧ページに表示させない。という実装を行いたいです。

2020-12-16 08:59 UTC, ajk0421 commented
>指定外のテキスト教材は一覧ページに表示させない。という実装を行いたいです。

理解しました！ではスコープを定義して実装しましょう！
下記が参考リンクになります！指定のデータだけ取れるようにしましょう！



- https://qiita.com/ozin/items/24d1b220a002004a6351

2020-12-17 04:22 UTC, ajk0421 requested changes

2020-12-17 04:22 UTC, ajk0421 commented on app/models/text.rb
> +  scope :recent, -> { specific_genre.sorted }
```
scope :recent, -> { specific_genre.sorted }
```
`recent = 最近` という意味なので、今回の実装内容には沿った名前ではない気がしますね。。

2020-12-17 05:12 UTC, yusaku9106 commented on app/models/text.rb
> +  scope :recent, -> { specific_genre.sorted }
コメントありがとうございます！
  私も単語の意味は理解しつつも、いただいたqiitaの記事、及び手元のrails実践速習ガイドのどちらもrecentとなっており、結合後のscopeはrecentとすべきなのか？と疑問を持ちつつ、プルリクあげてしまいました。。(プルリク時のコメント内の質問に、予め記載しておくべきでした。。。すみません。。)

2020-12-18 02:04 UTC, ajk0421 commented on app/models/text.rb
> +  scope :id_sorted_only_specific_genre, -> { specific_genre.sorted }
今回はスコープを理解することが目的でもあるので、これ良いですが！
```
id_sorted_only_specific_genre
```
ちょっと名前長いですね！笑

難しいとこですが、意味合い取って
```
Text.basics
```
とかでも良いかもしれませんね！

2020-12-18 02:04 UTC, ajk0421 approved these changes
OKです！マージしてください！

2020-12-18 06:49 UTC, merged

2020-12-18 06:53 UTC, yusaku9106 commented on app/models/text.rb
> +  scope :id_sorted_only_specific_genre, -> { specific_genre.sorted }
ありがとうございます！
あまり良い名前が思い付かず、、、
参考にさせていただきます！