17_Rails動画教材ページの実装
yanbaru-expert/gyakuten_clone_group36 pull request #22
Opened 2020-12-29 04:27 UTC by OKIfighter-FIRE

## 17_Rails動画教材ページの実装

- csv_data 出力
  - movies_contoller.rb 作成
  - models/movie.rb 編集

## 参考資料

Qiita Ruby CSVを扱うためのメモ

- Qiita 
  - https://qiita.com/shizuma/items/7719172eb5e8c29a7d6e

## チェックリスト

※ プルリクを出した後にクリックしてチェックを入れて下さい

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

## スクリーンショット（必要があれば）

## 備考（必要があれば）
movie_data.csv ファイルのデータを出力したいのですが動作確認の為【Rails/動画教材】 ページを開いても反映させてないので、コードのご確認を宜しくお願い致します！

2021-01-12 13:01 UTC, ajk0421 commented
>1:動画左上の /movies/1/edit を消したい

この行が原因ですね！erbのRubyの書き方をもう一度見直してみましょう！
https://github.com/yanbaru-expert/team_project_36/pull/22/files#diff-cedcac3030c71e3f9fcd2398449823143500d35c7c2825cf833e5d1742f5ce9aR5

>2:動画教材どうし高さを修正したい

ここはcssで直接高さを指定してあげましょう！

2021-01-16 01:18 UTC, OKIfighter-FIRE commented
## conflict解消

-app/stylesheets/application.scss コンフリクト解消致しました

ご確認宜しくお願い致します！

2021-01-16 08:49 UTC, ajk0421 commented on app/assets/stylesheets/application.scss
> +/* ログイン画面 */
このコメントは何故追加しましたか？

2021-01-16 08:50 UTC, ajk0421 commented on app/views/movies/index.html.erb
> +                      </div>
```
<iframe width="560" height="315" alt="<%= movie.title %>" src="https://www.youtube.com/embed/iFMNUM2Q9mg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe>
```
このコードだと、同じ動画が並ぶだけじゃないでしょうか？？

2021-01-16 08:56 UTC, ajk0421 requested changes
この辺って変更差分ありますが、なにかツールによって自動変更されてませんか？
```
- db/seeds.rb
- db/csv_data/question_data.csv
- config/routes.rb
```

このへんは不要なファイルですね！
```
- app/views/movies/index.html.erb.tmp
- app/views/layouts/_header.html.erb.tmp
```

2021-01-16 11:55 UTC, OKIfighter-FIRE commented on app/assets/stylesheets/application.scss
> +/* ログイン画面 */
特に意味はないです！

2021-01-16 11:57 UTC, OKIfighter-FIRE commented on app/views/movies/index.html.erb
> +                      </div>
確かに動画教材の後に他のリンクをクリックしたら動画教材のリンクがずっと表示されてました💦
修正方法調べてみます！

2021-01-16 12:03 UTC, OKIfighter-FIRE commented
> この辺って変更差分ありますが、なにかツールによって自動変更されてませんか？
> 
> ```
> - db/seeds.rb
> - db/csv_data/question_data.csv
> - config/routes.rb
> ```
> 
> このへんは不要なファイルですね！
> 
> ```
> - app/views/movies/index.html.erb.tmp
> - app/views/layouts/_header.html.erb.tmp
> ```



>> - db/seeds.rb
> - db/csv_data/question_data.csv
> - config/routes.rb
> ```
特にツールを使った覚えはありません💦

2021-01-16 22:09 UTC, ajk0421 commented on app/assets/stylesheets/application.scss
> +/* ログイン画面 */
意味がないのであれば追加しなくて良いと思います！

2021-01-16 22:13 UTC, ajk0421 commented
>特にツールを使った覚えはありません💦どうしたら変更差分の確認が出来るのでしょうか？ご教授宜しくお願い致します。

差分確認はPRを見てますよ！
PRの差分を見て、ご自分の修正した記憶の無い部分が差分として出ていないでしょうか？
特に僕のあげた
```
- db/seeds.rb
- db/csv_data/question_data.csv
- config/routes.rb
```
このへんのファイルって今回ご自分で修正されましたか？

2021-01-18 05:05 UTC, OKIfighter-FIRE commented
> > 特にツールを使った覚えはありません💦どうしたら変更差分の確認が出来るのでしょうか？ご教授宜しくお願い致します。
> 
> 差分確認はPRを見てますよ！
> PRの差分を見て、ご自分の修正した記憶の無い部分が差分として出ていないでしょうか？
> 特に僕のあげた
> 
> ```
> - db/seeds.rb
> - db/csv_data/question_data.csv
> - config/routes.rb
> ```
> 
> このへんのファイルって今回ご自分で修正されましたか？


----------------------------------------------
> - config/routes.rb で `  resources :movies
`は追加しましたが他のファイルを触った覚えは特にありません💦

2021-01-18 05:29 UTC, OKIfighter-FIRE commented on app/views/movies/index.html.erb
> +                      </div>
><iframe width="560" height="315" alt="<%= movie.title %>" src="https://www.youtube.com/embed/iFMNUM2Q9mg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe>

このコードだと、同じ動画が並ぶだけじゃないでしょうか？？
-------------------------------------------------------------
現在動画は同じものが並ばなく表示されてますが、動画教材ページの次のページをクリックすると同じ動画教材のページしか表示されず詰まっております💦

例)Rails動画教材→PHP教材ページをクリックしてもRails動画教材ページがそのまま表示されブランクページになりません

こういった場合、rails 動画 each 分で調べてみましたがあってますでしょうか？rails 動画 hash などで調べてみてもうまく使い方を見つけれません、ご教授宜しくお願い致します！

2021-01-18 05:34 UTC, OKIfighter-FIRE commented
> > 特にツールを使った覚えはありません💦どうしたら変更差分の確認が出来るのでしょうか？ご教授宜しくお願い致します。
> 
> 差分確認はPRを見てますよ！
> PRの差分を見て、ご自分の修正した記憶の無い部分が差分として出ていないでしょうか？
> 特に僕のあげた
> 
> ```
> - db/seeds.rb
> - db/csv_data/question_data.csv
> - config/routes.rb
> ```
> 
> このへんのファイルって今回ご自分で修正されましたか？

2021-01-19 10:41 UTC, OKIfighter-FIRE commented
## 指摘箇所の修正

`<iframe width="560" height="315" alt="<%= movie.title %>" src="https://www.youtube.com/embed/iFMNUM2Q9mg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe>`

-----------------------------------------------
- db/seeds.rb
- db/csv_data/question_data.csv
- config/routes.rb
-----------------------------------------------
二箇所修正致しました、ご確認宜しくお願い致します！

2021-01-21 13:34 UTC, ajk0421 approved these changes
OKです！マージしてください！

2021-01-21 23:36 UTC, merged