1.環境開発の整備
yanbaru-expert/gyakuten_clone_group36 pull request #5
Opened 2020-11-28 11:40 UTC by OKIfighter-FIRE

【注意】不要なものは削って下さい

## 環境開発の整備

原則，マークダウン記法のリストで記載すること

- 環境開発の整備
  - pry-byebug_installed
  - config/initializers/generators.rb_作成

## 参考資料

マークダウン記法のリンクを用いて記載すること

## チェックリスト

※ プルリクを出した後にクリックしてチェックを入れて下さい

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

## スクリーンショット（必要があれば）

## 備考（必要があれば）

2020-11-28 11:43 UTC, OKIfighter-FIRE commented
すみません、ブランチ名 feature/ 付けずに作成してしましました💦
宜しくお願い致します！

2020-11-28 23:55 UTC, ajk0421 requested changes

2020-11-28 23:55 UTC, ajk0421 commented on Gemfile
> +
ここに余計な空行が入っているので削除しましょう！余計な差分が出ない様にしましょう！

2020-11-29 02:51 UTC, ajk0421 approved these changes
LGTMです！
マージしてください！

2020-11-29 03:16 UTC, merged